/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import clientews.Cliente;
import clientews.ClienteService;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josel
 */
public class GUI extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(jButton1)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(88, 88, 88)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.jTextField1.getText().equals("")) {
            this.cargarTabla();
        } else {

            this.buscar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    String[] titulos = {"ID", "Nombre", "Apellido1", "Apellido2", "Tipo Documento", "N. Documento", "Sexo", "Fecha Nacimiento", "Direccion", "Codigo Postal", "Estado Civil"};

    public void cargarTabla() {
        try {
            String[] registros = new String[11];
            modelo = new DefaultTableModel(null, titulos);
            ClienteService lista = new ClienteService();
            List<Cliente> rs = lista.getBasicHttpBindingIClienteService().listarCliente().getCliente();
            for (int i = 0; i < rs.size(); i++) {
                registros[0] = rs.get(i).getIdCliente().toString();
                registros[1] = rs.get(i).getNombre().getValue();
                registros[2] = rs.get(i).getApellidoPaterno().getValue();
                registros[3] = rs.get(i).getApellidoMaterno().getValue();
                registros[4] = rs.get(i).getTipoDocumento().getValue();
                registros[5] = rs.get(i).getNumeroDocumento().getValue();
                registros[6] = rs.get(i).getSexo().getValue();
                registros[7] = rs.get(i).getFechaNacimiento().toString();
                registros[8] = rs.get(i).getDireccion().getValue();
                registros[9] = rs.get(i).getCodigoPostal().getValue();
                registros[10] = rs.get(i).getEstadoCivil().getValue();
                modelo.addRow(registros);
            }
            jTable1.setModel(modelo);
        } catch (Error ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }
    }

    public void buscar() {
        try {
            modelo = new DefaultTableModel(null, titulos);
            String[] registros = new String[11];
            ClienteService lista = new ClienteService();
            Cliente rs = lista.getBasicHttpBindingIClienteService().obtenerCliente(this.jTextField1.getText());
            registros[0] = rs.getIdCliente().toString();
            registros[1] = rs.getNombre().getValue();
            registros[2] = rs.getApellidoPaterno().getValue();
            registros[3] = rs.getApellidoMaterno().getValue();
            registros[4] = rs.getTipoDocumento().getValue();
            registros[5] = rs.getNumeroDocumento().getValue();
            registros[6] = rs.getSexo().getValue();
            registros[7] = rs.getFechaNacimiento().toString();
            registros[8] = rs.getDireccion().getValue();
            registros[9] = rs.getCodigoPostal().getValue();
            registros[10] = rs.getEstadoCivil().getValue();
            modelo.addRow(registros);
            jTable1.setModel(modelo);
        } catch (Error ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
